server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
#    auth-service:
#      path: /auth-api/**
#      serviceId: auth-service
    product-service:
      path: /product-api/**
      serviceId: product-info
    order-service:
      path: /order-api/**
      serviceId: order


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000


# MySQL config
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_NAME:msjwttest}
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:infosys}
